### ISSUE TITLE
特定のパターンの文章を食わせるとprevが参照できずに落ちる

### ISSUE THREAD

**Issue by vvakame** [vvakame/reviewjs-prh#2]
以下のようなパターンが処理できない

```
= test

//emlist{
あ
//}
```

```
TypeError: Cannot read property 'prev' of undefined
    at /Users/vvakame/.atom/packages/language-review/node_modules/reviewjs-prh/lib/index.js:57:30
    at Object.walk (/Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:5:16)
    at Object.ReVIEWWalker.visit.visitTextPre (/Users/vvakame/.atom/packages/language-review/node_modules/reviewjs-prh/lib/index.js:56:30)
    at /Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:325:25
    at _visitSub (/Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:335:11)
    at /Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:112:55
    at /Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:390:56
    at Array.map (native)
    at SyncTaskPool.consume (/Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:390:27)
    at /Users/vvakame/.atom/packages/language-review/node_modules/review.js/lib/parser/walker.js:120:25
```

from https://github.com/vvakame/language-review/issues/36

**Comment by vvakame** [comment]
うーんreview.js側を改善したほうがよかった…
